Changed to storing TOKEN instead of userid and password
goweiwen/ivle-sync pull request #3
Opened 2018-01-16 03:01 UTC by indocomsoft

This is my first time actually writing python, so do let me know if there are any styling issues.

Basically instead of storing userid and password, if there isn't any TOKEN key in credentials.json, the script will ask for for user to type in userid and password, obtain TOKEN and write it to credentials.json. Otherwise it would extract the TOKEN from credentials.json.

2018-01-16 05:12 UTC, goweiwen commented
Thanks for contributing! I use [yapf](https://github.com/google/yapf) for formatting this repo. It should settle all styling issues for you.

I don't think we can store the token and reuse it forever. According to the [IVLE LAPI wiki](https://wiki.nus.edu.sg/display/ivlelapi/Login), the token they return expires. Ideally, we want to store the token together with its expiry date, and reuse that until it expires.

Writing directly to credentials.json is a good feature, but we should prompt the user if they wish to save their credentials and/or allow them to change/reset it easily (from the CLI).

2018-01-17 11:44 UTC, indocomsoft commented
Thanks for the feedback. I used yapf but it seems that it re-formatted existing code as well. Let me know if you would like me to revert existing code to original formatting.

The way I implement it now:

- Added a feature to clear-token (./ivle.py clear-token).
- If there is TOKEN in credentials.json, use the Validate LAPI.
    - If not valid, clear token in credentials.json and obtain new token.
    - If provided with a new token, write it to credentials.json (a new token is issued if the original token is expiring in one day)
- If there is no TOKEN in credentials.json, then obtain new token.

During the process of obtaining a new token, user will be asked whether they want to store the token in credentials.json

Let me know if you have any feedback regarding this.

2018-01-17 13:06 UTC, goweiwen requested changes
Wow! Great work! Just a few changes before we can merge this.

Thanks for all the hard work!

(I think the mismatched formatting is from YAPF for Python 2. You should install the Python 3 version.)

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +            if not r["Success"]:
Should be single-quoted

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +                    "New token obtained -- old token is expiring in one day.")
I don't think the user needs to be informed about implementation details like this

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +    def new_token(self):
Should be a verb

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +    userid = input("UserID: ")
I think we should still allow users to store credentials in the config because we only receive a new token one day before it expires (I don't use it everyday myself).

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +            "Do you want to write the token obtained to credentials.json?[y/n] "
"Do you want to write the token obtained to credentials.json? [y/N] "
to denote a default choice

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +        elif choice in no:
Since this is not an irreversible action, it is okay to have a default option which should be `n`

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +def yes_no():
This function is only used for asking whether we should save the token, so it should be named appropriately

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +        if yes_no():
Sorry for the miscommunication, I feel we should only prompt them if we're saving credentials (as they are quite sensitive). For tokens, it is fine to leave the user logged in.

2018-01-17 13:06 UTC, goweiwen commented on ivle-sync.py
> +    print("Usage: " + argv[0] + " [files|announcements|clear-token]")
`clear-token` sounds a little ambiguous to me. Would `logout` or `reset` work better?

2018-01-18 01:29 UTC, indocomsoft commented
Followed all your suggestions!

I formatted using yapf for python3, and there was indeed one `folder. print` vs `folder.print` difference. However for the rest, there is no change, but tbh the newer formatting is saner.

I also added get_lapi_key() so user does not have to edit credentials.json manually anymore. I am thinking that it would be best that the script generate credentials.json when the config file does not exist? (so that the script will be independent of the presence of credentials.json)

2018-01-18 04:02 UTC, goweiwen commented
Looks good, thanks for the work!

Automatically generating the file can be done in another PR, so I'll merge this first.

2018-01-18 04:02 UTC, merged